// <auto-generated />
using FYPJ4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FYPJ4.Migrations
{
    [DbContext(typeof(FYPJ4Context))]
    [Migration("20181227085253_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FYPJ4.Models.News", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountCode");

                    b.Property<string>("AccountDesc");

                    b.Property<string>("Actual");

                    b.Property<string>("Encumbrance");

                    b.Property<string>("FYBalance");

                    b.Property<string>("FYBudget");

                    b.Property<string>("FYSpent");

                    b.Property<string>("FYSpentPercent");

                    b.Property<string>("ReportAsAt");

                    b.HasKey("ID");

                    b.ToTable("News");
                });
#pragma warning restore 612, 618
        }
    }
}
